### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by lacalamine64** [gluap/pyduofern-hacs#14]
Hi @gluap,

since updating from core-2021.12.3 to 2021.12.5 I can't interact with my shutters anymore.
Even the updates to .6 and.7 didn't fix it.

Could you help me to find out why?

Edit: I had the title "Shutters not working anymore since updating core" but that wasn't saved.

**Comment by gluap** [comment]
I'm going to upgrade my own installation - I usually only do that every one or two months as it's not an internet-connected homeassistant. If you're lucky I it will fail for me too and I will roll out a fix - otherwise I'll get back to you with questions to find out what's different on your end.

**Comment by bcutter** [comment]
Spoiler: with HA 2021.12.6 everything's working fine with DuoFern integration. Didn't check the logs for new related entries but everything fully functional as before.

Depending on how you host HA: any HASS OS update is basically more suspicious because sometimes they change USB relevant stuff there.

**Comment by lacalamine64** [comment]
Hey, thanks for your fast reply.

After some reboots of the whole system it worked again and when I came back home, everything stopped working.

I think the drive died so for now I have to restore everything. Maybe that was the cause for my problems.

I will reply back if it works again after restoring.

**Comment by bcutter** [comment]
@lacalamine64 Do you want to close this issue?

**Comment by lacalamine64** [comment]
Hi, sorry for replying that late. After I had to re-setup everything it seems to work again. Thanks for your help.
