### ISSUE TITLE
State change of many devices at the same time

### ISSUE THREAD

**Issue by rakragh** [gluap/pyduofern-hacs#15]
First of all thank for providing us that solution.
I ran into a problem changing the state of many devices at the same time. Some devices are getting ignored hereby. After splitting in two or three separate automations which run with offset it works. On the other hand, if the automations run in parallel, it doesn't work again. Any ideas?

**Comment by bcutter** [comment]
No ideas. Just to add:

- I see sometimes the state is not updated in HA, e. g. when controlling the devices locally. Sometimes HA would never know that state has changed.

- For the issue you describe: I can not confirm it. When I pass one command to a cover group containing all my RolloTron blinds, one by one they start to react (seems like the command is sent sequentially by the sender).

**Comment by gluap** [comment]
I'll close this as it wasn't reproducible - feel free to reopen with a way to reproduce or logfiles of the issue.
