### ISSUE TITLE
New release with latest changes?

### ISSUE THREAD

**Issue by nodomain** [gluap/pyduofern-hacs#20]
Hi,

when do you plan to create a new release, e.g. 0.22 to be available in HACS?

Thx

**Comment by 8OND007** [comment]
is there a new version 0.22 ? I can seem to find it.
Latest was 0.2.0 and if I look onto Github: version 0.3.0 as a prerelease (Merge pull request https://github.com/gluap/pyduofern-hacs/pull/19 from Hypfer/patch-1) where SUPPORT_OPEN, SUPPORT_CLOSE, SUPPORT_SET_POSITION, SUPPORT_STOP was added in HA Cover.
It would be nice to see the Duofern custom HA integration be migrated to a HA Addon where pyduofern communicates with a MQTT broker and put the Cover there (bidirectional entitities Cover).

**Comment by gluap** [comment]
Took this as a hint to remove the pre-release tag from 0.3,so it should be available on hacs now. The beta was online for quite a while without complaints.
