### ISSUE TITLE
Provide pre-releases in HACS

### ISSUE THREAD

**Issue by bcutter** [gluap/pyduofern-hacs#22]
Could you please list the pre-releases as beta versions in HACS?

There should be a flag for beta releases.

Couldn't find 0.3.3 / 0.3.4 I would like to test.

![image](https://user-images.githubusercontent.com/13799156/210137147-89cbf5f3-9995-47cb-8f8d-5819144dde5e.jpeg)

**Comment by gluap** [comment]
@bcutter works on my side - maybe you could try again? I had to yank the 0.3.4 for a minute or so because it wasn't working, maybe that was right when you tried to  install?
![image](https://user-images.githubusercontent.com/44007906/210139990-a15c14d8-e97f-48f3-93b7-c0bf40a0ee33.png)

**Comment by bcutter** [comment]
Now it was shown - maybe HACS hasn't updated its repositories yet. Installed, reboot and tests pending.
