### ISSUE TITLE
DUOFERN receives unknown message during setup

### ISSUE THREAD

**Issue by Spartacus68** [gluap/pyduofern-hacs#25]
Hi,
I have installed the DIUFERN Stick in my current HA . The Rollo-Tube is connected in fhem with the stick. When I switch to HA and try to start from scatch, an error message occurs and the UI does not have anything to start configuration. If i open the services manually (Duofern control: start_pairing) nothing happens.

```
Log Message:
Logger: /usr/local/lib/python3.10/site-packages/pyduofern/duofern.py
Source: /usr/local/lib/python3.10/site-packages/pyduofern/duofern.py:551
First occurred: 13:39:53 (1 occurrences)
Last logged: 13:39:53

DUOFERN unknown msg: 0fff0f2c63005a1a110000000000ff49d5f2ffffff01
```

**Comment by gluap** [comment]
Hi @Spartacus68, I know that Homeassistant makes these look like errors, but actually [it's just a "Warning" message](https://github.com/gluap/pyduofern/blob/master/pyduofern/duofern.py#L551) and not something that crashes pyduofern. These happen from time to time - more often if Devices not supported by pyduofern are around (like the weather station for instance).

It is normal that "nothing [obvious] happens" (in Homeassistant) after running ``start_pairing``. There is simply no UI for configuration of individual duofern blinds, the only interface is calling services. For homeassistant to pick up the new devices a ``duofern.sync_devices`` is required - and a homeassistant restart may be in order. The motivation for the services is simply that some users don't have access to their command line.

If you used FHEM before it may make sense to use the same system code as in FHEM (strip the first two characters which were fixed to always the same value there anyhow).

**Comment by Spartacus68** [comment]
Hi,

sorry for disturbing you again!

What I noticed is, that the position detection from your 
DUOFERN-implementation is different to other implementations. All 
shutter devices in fhem (DUOFERN, Eltako, Peha etc) have:

0% for open
100%. for closed.

It´s a little bit strange to have differnt position styles on the same 
environment (enocean in HA works also with 100% for closed). Maybe you 
can implement a feature to configure these parameters as you can do e.g. 
in the mqtt cover - entity.

Thanks for your great support,
Spartacus


------ Originalnachricht ------
Von "gluap" ***@***.***>
An "gluap/pyduofern-hacs" ***@***.***>
Cc "Spartacus68" ***@***.***>; "Mention" 
***@***.***>
Datum 31.01.2023 18:27:37
Betreff Re: [gluap/pyduofern-hacs] DUOFERN receives unknown message 
during setup (Issue #25)

**Comment by gluap** [comment]
I'll add a reminder that there's no pairing gui to the service docstring. 

Somebody reported success with a 10-digit device [over in the backend](https://github.com/gluap/pyduofern/issues/31#issuecomment-1222693774). As for implementation the maximum I was planning for was to wait if it will be implemented in FHEM and see if I can port it from there. pyduofern is a very incomplete python port of fhem-duofern anyhow. 

According to the [homeassistant documentation](https://www.home-assistant.io/integrations/cover.template/) ![Screenshot_20230131-211624~2.png](https://user-images.githubusercontent.com/44007906/215872879-30137d2c-2cf5-40b4-9926-9e49c3392d98.png), 0% means closed - so its likely consistent within homeassistant, maybe with a few outliers. Unfortunately I can't easily make it configurable, the whole reason there is no GUI for pairing is that it took me forever to even get the setup GUI working - I had a hard time wrapping my head around the way to create individual ui in homeassistant. I just seem to break it whenever I touch it. Which is likely my fault for being more of a backend person.

**Comment by Spartacus68** [comment]
Hello,

ah, ok! Thanks for the hint with the 10digit! I left a post in the fhem 
forum <https://forum.fhem.de/index.php?topic=40076.1126> some days ago 
but the developer was not aware of this topic...He is waiting for me and 
the new Rademacher tubes 🙂! But before I buye a new "Rollotube s-line 
duofern" -Device for testing porpose, I have to migrate all my existing 
devices to HA...and  this will take some time! I hope anyone else will 
test the 10digit before!

As long as I there are differences in the position handling for open and 
close, I will run DUOFERN via fhem and mqtt-bridge  as I do it for some 
1-wire and Enocean-Devices. But in a long term I will replace the 
enocean and 1-wire devices with zigbee, matter  and DUOFERN Devices. 
Latest then, i will decommission the stale fhem.

I would very much appreciate, if you can implement a configuration for 
the position handling.

Many, many thanks and have a nice evening,
Christian

P.S:: What I aslo noticed is, that DUOFERN is not sending the position 
continuously, as e.g. enocean PEHA 452 FU-EBIM JR o.T. does. It seems to 
be that this is a limitation of the Rademacher DUOFERN-Devices which 
lthen eads to a strange visualization when moving the shutters. Not sure 
if this works as disigned!


------ Originalnachricht ------
Von "gluap" ***@***.***>
An "gluap/pyduofern-hacs" ***@***.***>
Cc "Spartacus68" ***@***.***>; "Mention" 
***@***.***>
Datum 31.01.2023 21:35:00
Betreff Re: [gluap/pyduofern-hacs] DUOFERN receives unknown message 
during setup (Issue #25)

**Comment by gluap** [comment]
The "moving" state of shutters is only in the beta -  it's behaving a bit strangely so i'm planning to take it out again. For me, the shutters often get stuck in a "moving" state. I guess that duofern does not guarantee transmission of messages and therefore if a "stopped" message is lost it might just be lost.
