### ISSUE TITLE
Some covers not closing reliably (commands likely not received)

### ISSUE THREAD

**Issue by bcutter** [gluap/pyduofern-hacs#33]
Every day a "close all covers" automation runs a script which actually closes all covers (basically by in the end using `service: cover.close_cover` on `entity_id: cover.rollladen_alle` which is a group containing all cover entities).

That worked just perfect all the time - I mean, for YEARS. Today I experienced this:

3 covers did not close. Actually, they did not even start to do something.

(1) automation trace:
![grafik](https://user-images.githubusercontent.com/13799156/228929205-8929439c-a8fa-4707-a4c7-8d6ac1c39ac9.png)

(2) script trace:
![grafik](https://user-images.githubusercontent.com/13799156/228924546-d3190c29-be88-4155-841b-c5ead61e44be.png)

(3) result in GUI:
![grafik](https://user-images.githubusercontent.com/13799156/228924645-5a541f2c-405f-44f5-b485-49ed69f1a58b.png)

Nothing in home-assistant.log (next to the usual `er.5 is not a valid duofern device` in #31 because of running `service: duofern.ask_for_update` at the end of the script - after the close all covers section) and of course debugging was not enabled during that time.

---

Even ignoring latest "first time issue" #32, I start to see a pattern with running duoFERN 0.4.3 for a week now, summing up in **_everything is much less reliable_**. I spent so much time for newly introduced issues... which is fine as those are beta versions which obviously need input from users testing them in their productive environment. Current main issues not being present with 0.4.0:
- service not working for multiple/all covers #31
- covers not updating their state for minutes or even hours (regardless of the 5 minutes auto update thing introduces with 0.4.1) https://github.com/gluap/pyduofern-hacs/issues/31#issuecomment-1484171160
- now covers not reacting at all (this issue)

Really, the only thing changed is duoFERN version being updated from 0.4.0 to 0.4.3 (with a short step at 0.4.1).

---

My wild theory for this issue:
During the command "close cover" sent from the stick to all covers, the affected 3 of them were already sending their device state to the stick according to the mysterios "5 minute auto update feature" (see #26) which proven creates some constant noise when looking at the integration debug log. Therefore they did not receive the close command and did - nothing.
- Is the protocol bidirectional?
- Or is Alice blocking incoming transmission from Bob during the time Alice is sending messages to Bob?

Workaround: running the script a second time manually made the 3 affected covers being closed.

Please
a) make the `duofern.ask_for_update` service able to work with multiple/all covers again #31 
b) urgently rethink #26 🙏 and allow to disable it / set a custom interval (including zero)

**Comment by gluap** [comment]
@bcutter Looking into #31 I found an easy way to implement the "customizer" service you've been asking for in #26. In my initial investigation I thought that I would have to manually thread the interval through many levels of code, but now found an ugly but working solution by just monkeypatching the value onto the duofernstick object which is available to both the services and in the duofern devices. That reduced the implementation time from hours to a few minutes.

v0.5.3 therefore release should adress a) and b).

**Comment by gluap** [comment]
I'm sorry to disappoint but:
- magic all will probably not work - unless that's a homeassistant-integrated feature. 
- update interval state is not persisted. I'd suggest using it like this:
![image](https://user-images.githubusercontent.com/44007906/229178279-d9ffb7f2-135b-48db-a94f-1bf0bd5cf16b.png)

**Comment by gluap** [comment]
updating all is an option now (was easier and probably more intuitive to do it like this:) 
![image](https://user-images.githubusercontent.com/44007906/229195324-1ba60c5b-f082-472c-bbe2-235b9a5a39fb.png)

**Comment by bcutter** [comment]
Quick feedback (final one arriving in a few days after monitoring new behaviour/stability) after updating from 0.4.3 to 0.5.4 two hours ago:

1) ✔ No disabling/re-enabling of integration needed. Devices and new entities were there right after HA startup finished.
2) ✔ `duofern.set_update_interval` seems to work (accepting `0`, using longer update intervals like 15 or even 60 not tested yet)
3) ✔ GUI field `device_id` for the `duofern.ask_for_update` service now lists all entities. Could be limited to `cover.*` entities only (to filter the manual mode and toggle entities which make the UI just filling up without benefits - tbh I don't really care 😃)
4) ✔ `duofern.ask_for_update` accepts multiple entities
5) ❓ Using `duofern.ask_for_update` without specifying `device_id` nor `all` gives no error, but it will likely do... nothing, right?
6) ❌ Unfortunately `duofern.ask_for_update` does NOT accept `all` with `all: true`. I'll create a separate issue for that. See #35 

I'll turn back in a few days so we can hopefully close few issues based on "long-term" experiences.

**Comment by gluap** [comment]
regarding 5): Yes, calling it with nothing will do nothing.
regarding 6:) I think that error is a follow-up error of the bogous devices you mentioned that have appeared in your duofern config. I'll address it in #35

**Comment by gluap** [comment]
I see all the remaining questions were addressed
