### ISSUE TITLE
duofern component cannot be loaded

### ISSUE THREAD

**Issue by Spartacus68** [gluap/pyduofern-hacs#39]
The duofern component cannot be loaded since HA update to 2023.6.3

Log:
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: homeassistant.setup
Source: custom_components/duofern/__init__.py:47
Integration: Duofern control (documentation, issues)
First occurred: 10:49:23 (1 occurrences)
Last logged: 10:49:23

Error during setup of component duofern
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 286, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/duofern/__init__.py", line 47, in setup
    from pyduofern.duofern_stick import DuofernStickThreaded
ImportError: cannot import name 'DuofernStickThreaded' from 'pyduofern.duofern_stick' (/usr/local/lib/python3.11/site-packages/pyduofern/duofern_stick.py)

**Comment by gluap** [comment]
Which version of duofern are you using?

**Comment by Spartacus68** [comment]
Hi,
I am using 0.4.3. and I re-installed it today. But the saame issue.
Christian


------ Originalnachricht ------
Von "gluap" ***@***.***>
An "gluap/pyduofern-hacs" ***@***.***>
Cc "Spartacus68" ***@***.***>; "Author" 
***@***.***>
Datum 04.07.2023 14:05:22
Betreff Re: [gluap/pyduofern-hacs] duofern component cannot be loaded 
(Issue #39)

**Comment by gluap** [comment]
It was already fixed in the beta, so with the beta now dry-aged for a few months I marked the beta as stable.

Take care to read the release notes! 0.5.0 brings a bunch of changes and improvements.

**Comment by Spartacus68** [comment]
Hi,

thanks for doing that,
I am using now  0.5.7.
I have removed the component and reinstalled it, but it is still the 
same issue and not working.


Log:

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: homeassistant.setup
Source: custom_components/duofern/__init__.py:55
Integration: Duofern control (documentation, issues)
First occurred: 20:37:34 (1 occurrences)
Last logged: 20:37:34

Error during setup of component duofern
Traceback (most recent call last):
   File "/usr/src/homeassistant/homeassistant/setup.py", line 286, in 
_async_setup_component
     result = await task
              ^^^^^^^^^^
   File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 
58, in run
     result = self.fn(*self.args, **self.kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/config/custom_components/duofern/__init__.py", line 55, in 
setup
     stick = DuofernStickThreaded(serial_port=serial_port, 
system_code=code, config_file_json=configfile,
             
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File 
"/usr/local/lib/python3.11/site-packages/pyduofern/duofern_stick.py", 
line 442, in __init__
     super().__init__(*args, **kwargs)
   File 
"/usr/local/lib/python3.11/site-packages/pyduofern/duofern_stick.py", 
line 105, in __init__
     assert self.config['system_code'].lower() == system_code.lower(), \
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: System code passed as argument "D5F2" differs from 
config file "1A2B", please manually change the config file 
/config/duofern.json if this is what you intended. If you change the 
code you paired your devices with you might have to reset them and 
re-pair.



------ Originalnachricht ------
Von "gluap" ***@***.***>
An "gluap/pyduofern-hacs" ***@***.***>
Cc "Spartacus68" ***@***.***>; "Author" 
***@***.***>
Datum 04.07.2023 20:02:13
Betreff Re: [gluap/pyduofern-hacs] duofern component cannot be loaded 
(Issue #39)

**Comment by gluap** [comment]
The error message has changed - it seems that you have two contradicting system codes configured. Fixing that should fix the issue. 

refer to the last sentence of the error message:
```
AssertionError: System code passed as argument "D5F2" differs from config file "1A2B", please manually change the config file /config/duofern.json if this is what you intended. If you change the code you paired your devices with you might have to reset them and re-pair.
```

**Comment by Spartacus68** [comment]
Hi,

I changed this but it doesn´t help! The device cannot be found anymore. 
With fhem everything is fine and the tube is running.

Here my config:
{
     "devices": [
         {
             "id": "49d5f2",
             "name": "49d5f2"
         }
     ],
     "system_code": "d5f2"
}


------ Originalnachricht ------
Von "gluap" ***@***.***>
An "gluap/pyduofern-hacs" ***@***.***>
Cc "Spartacus68" ***@***.***>; "Author" 
***@***.***>
Datum 05.07.2023 08:23:20
Betreff Re: [gluap/pyduofern-hacs] duofern component cannot be loaded 
(Issue #39)

**Comment by gluap** [comment]
So the error message is still 

> AssertionError: System code passed as argument **D5F2** differs from config file **1A2B**, please manually change the config file /config/duofern.json if this is what you intended. If you change the code you paired your devices with you might have to reset them and re-pair.?

**Comment by Spartacus68** [comment]
Hi,

no, there is no more error message. It is installed correctly, but it 
does not work. HA says it works, and I can see the entities  but the 
shutter does not move a millimeter.
When I switch to fhem, everything is fine!

Christian

------ Originalnachricht ------
Von "gluap" ***@***.***>
An "gluap/pyduofern-hacs" ***@***.***>
Cc "Spartacus68" ***@***.***>; "Mention" 
***@***.***>
Datum 05.07.2023 16:30:26
Betreff Re: [gluap/pyduofern-hacs] duofern component cannot be loaded 
(Issue #39)

**Comment by gluap** [comment]
Are you using the same system code as in FHEM?

**Comment by gluap** [comment]
Also: have you tried pairing with homeassistant?

**Comment by Spartacus68** [comment]
Hi,

there is no field in fhem to configure a special system code (see 
below). So I think fhem is using the last 4 digits from the tube ID.  
This is  also configured in HA.  I have not tried to re-pair because if 
something goes wrong I have to open the shutter box and this is what I 
do not really want because it was painted fresh :-).

I think I have to switch off the duofern function  and have to install a 
shelly instead of this. The "kitchen" is the only duofern tube I have 
and the wireless connection to the tube is also not the best. I also do 
not believe that re-pairing will change anything because the DUOFERN 
stick is always the same on both VMs (fhem and HA)



------ Originalnachricht ------
Von "gluap" ***@***.***>
An "gluap/pyduofern-hacs" ***@***.***>
Cc "Spartacus68" ***@***.***>; "Mention" 
***@***.***>
Datum 05.07.2023 16:35:42
Betreff Re: [gluap/pyduofern-hacs] duofern component cannot be loaded 
(Issue #39)

**Comment by gluap** [comment]
The system code is a "secret number" that you chose yourself and is the same for all duofern devices - it is independent from your individual shutter ids. Only devices paired with the same system code will can be reached. So if your FHEM uses a different system code that would explain it. In the FHEM doku this code [is called "Duofern Code"](https://wiki.fhem.de/wiki/DUOFERNSTICK). It begins with "6F" followed by 4 digits that you likely have chosen during installation of FHEM. Those 4 digits must be the same in Homeassistant and FHEM.

If FHEM and Homeassistant use a different "Duofern Code", that will cause exactly the behavior you describe: Only one of the two will be able to move the shutter, in this case FHEM.

**Comment by Spartacus68** [comment]
Hi,

you´re totally right. There is a System-Code in fhem (I missed that, 
sorry). This is the "1A2B" from the DUOFERNSTICK which was originally 
configured in the duofern.json (Checked the backup from HA). But this 
configuration leads to the initial error in one of the first posts, this 
is what I do not understand....

Now I did the following steps:
I removed duofern from HACS
delete the duofern.json
restart HA
configuration of the Rollotube with the Systemcode above
restart HA ->  (no device available!!)
check duofern.json ->(no device ID available only the system ID, device 
ID empty)
replace the dufern.json with the original one from last week before the 
HA update
reboot HA
...then it works. It seems to be that the configuration is not working 
correctly.
Many thanks for your support. What is the "manual mode" doing?

Regards,
Christian

{
     "devices": [
         {
             "id": "49d5f2",
             "name": "49d5f2"
         }
     ],
     "system_code": "1A2B"
}


------ Originalnachricht ------
Von "gluap" ***@***.***>
An "gluap/pyduofern-hacs" ***@***.***>
Cc "Spartacus68" ***@***.***>; "Mention" 
***@***.***>
Datum 05.07.2023 17:12:08
Betreff Re: [gluap/pyduofern-hacs] duofern component cannot be loaded 
(Issue #39)

**Comment by gluap** [comment]
The manual mode was provided by a user - supposedly there are shutters where the local automation (on the duofern device) can be switched on or off using it. I have no way of testing as my shutters don't have that function.
