### ISSUE TITLE
duofern.sync_devices throws ‘ConfigEntries’ object has no attribute ‘async_setup_platforms’

### ISSUE THREAD

**Issue by mkm-gh** [gluap/pyduofern-hacs#42]
When starting the service duofern.sync_devices, I get the error

> AttributeError: ‘ConfigEntries’ object has no attribute ‘async_setup_platforms’

in /root/config/home-assistant.log

Can someone confirm this and/or provide a solution?

**Comment by gluap** [comment]
Yeah, can confirm. Workaround would be restarting homeassistant. it seems that the way to call for re-initialization of a platform has changed.

**Comment by mkm-gh** [comment]
I can now see the device, but not control it. The manual mode is turned off. All three entities do not react, i.e., e.g., I turn the manual mode on and it turns off automatically.

**Comment by gluap** [comment]
Sync devices should be fixed with the latest beta version. I'm afraid that does not necessarily fix your second problem though.

**Comment by mkm-gh** [comment]
Running `duofern.sync_devices` now throws

```
ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries-py", line 1385, in async_forward_entry_setup if domain not in self-hass.config. components:
TypeError: unhashable type: 'list'
```

**Comment by gluap** [comment]
Sync devices service (non-working) was removed in the latest sources (as it was not working anymore)
