### ISSUE TITLE
Home Assistant HACS Update duofern  from 0.3.2 to 0.5.8 - no control anymore

### ISSUE THREAD

**Issue by argonid** [gluap/pyduofern-hacs#43]
I have today updated HACS duofern from 0.3.2 to 0.5.8 and cannot control my duofern devices anymore.
I also cannot find under services "duofern.sync_devices" / "duofern.start_pairing".
Thanks for helping me so that I can control again my Rademacher devices.

**Comment by gluap** [comment]
Could you provide information on your setup?
- tried restarting homeassistant?
- any log messages regarding pyduofern?
- which version of homeassistant, which kind of deployment ("homeassistant core", "homeassistant os", "homeassistant supervised"?)
- if applicable: does the CLI work?

**Comment by argonid** [comment]
yes, restarted and I can see at least in the integration my devices / entities. 
Interesting is that the Rademacher 2 Channel actor works but my shutters/covers and my garage drive does not work.
When I click on one shutter it shows that it was closed 31 mins ago due to the automatic closing but when I click on the arrow up of one shutter it shows "Öffnet vor 31 sekunden" / opens 31 secs ago" and the arrow disappears.

Home Assistant

    Core 2023.11.2
    Supervisor 2023.11.3
    Operating System 10.5
    Frontend 20231030.2

**Comment by argonid** [comment]
Strange, I did the following and it works now. 
I clicked in my Rademacher Homepilot for every single device "Fernanmeldung Start" / "Remote registration" one after the other and in HA on "Duofern control: start_pairing".
Everything fine now.
Is it normal that for shutters the pairing is lost?

**Comment by gluap** [comment]
No, normally pairing is retained during upgrades. But with the upgrade to 0.5.x and the introduction of the new "devices" containing multiple entities, a lot of code pathes were changed. For me (and I assume also for others) this did not cause a loss of pairing, but maybe it happens in special conditions.

Glad to hear you were able to fix it!
