### ISSUE TITLE
Can't control shutters after power outage

### ISSUE THREAD

**Issue by chromos33** [gluap/pyduofern-hacs#54]
Had a Power outage last night and my homeassistant went down for like 15 minutes. 
When it rebooted it suddenly notified me of the system code not matching or something and shows me the current set and some other.
The integration doesn't load.

When I now edit the systemcode with ssh to the one specified by the notification the integration loads again but now the shutters won't react to input like down/up.

Is there anyway or do I have to pair them fresh?

A side note the shutters still accept commands from my old remote control

**Comment by gluap** [comment]
This sounds like the power outage caused some data corruption on your disk. Likely `.storage/core.config_entries` and `duofern.json` had different codes set.

It should work if you set the system code you have been using before the power outage (i can't tell which of the two files had the wrong code, but clearly one of the two must have deviated to give you this error message).

If you're doing backups before upgrades and haven't changed much you might wanna try replaying a backup.

**Comment by chromos33** [comment]
Thank you that was the issue added the code from the duofern.json to the other and now I can control the shutters again.
