### ISSUE TITLE
No 'version' key in the manifest file

### ISSUE THREAD

**Issue by rstephan** [gluap/pyduofern-hacs#6]
The log shows:
`WARNING (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'duofern'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'duofern'`

**Comment by gluap** [comment]
Hi @rstephan, thank you for reporting this, the version key is now set in the v1.1 release.
