### ISSUE TITLE
Update callback called on unknown device id

### ISSUE THREAD

**Issue by 8OND007** [gluap/pyduofern-hacs#9]
I get this warning since some time : 

Logger: custom_components.duofern
Source: custom_components/duofern/__init__.py:111
Integration: Duofern control (documentation, issues)
First occurred: 12:54:26 PM (13 occurrences)
Last logged: 12:54:26 PM
Update callback called on unknown device id

Where can I find some sort of debug log for pyduofern ? Or how do I active a debug log file for DuoFern communications ?

Since this warning is not always there, I suspect it's related to my Duofern SunSensor (RDUO 32000069) which send out "Sun Active" or "Sun Inactive" triggers over Duofern to my usb stick. 
Maybe this is a good chance to add this SunSensor to your pyduofern if I can send you the traces.

If I can send you the logs with ID's maybe the sunsensor is "identified" for good :-)

**Comment by gluap** [comment]
@bertdebondt Unfortunately the SunSensor neets its own Homeassistant device code implemented - so even if it identifies as good it won't show up in Homeassistant unless somebody writes the device classe - My guess is that this would be a "binary sensor" device.

**Comment by bcutter** [comment]
I get this warning too, even everything seems working. I don't use the SunSensor by the way.

**Comment by bcutter** [comment]
Again when restarting HAOS:

```
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.duofern
Source: custom_components/duofern/__init__.py:111
Integration: Duofern control (documentation, issues)
First occurred: 11:05:58 (26 occurrences)
Last logged: 11:05:59

Update callback called on unknown device id
```

**Comment by gluap** [comment]
I Demoted the message to "info" level. I don't think it's harmful so we can safely hide it.
